import type { Metadata } from "next";
import "./globals.css";
import { sora } from './ui/fonts';
import Header from "./ui/header/header";
import Footer from "./ui/footer/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} page`}>
        <Header></Header>
        <main className='main'>
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
